version: '3'
services:
  JoyceAdmin:
    container_name: JoyceAdmin
    build: .
    image: JoyceAdmin:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ep-mute-sunset-a4f9yh2u-pooler.us-east-1.aws.neon.tech
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - JoyceAdmin
  joyceadminAdminer:
    container_name: joyceadminAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - '9090:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=joyceadminDB
    networks:
      - joyceadmin
    depends_on:
      - JoyceAdminDB

volumes:
  joyceadmin-data:

networks:
  JoyceAdmin:
    name: Joyceadmin
    driver: bridge
